{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "f5fc62a6_bd864305",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1000602
      },
      "writtenOn": "2023-11-27T20:05:08Z",
      "side": 1,
      "message": "Hello Petr @phosek@google.com. Can you please review or assign a reviewer. The Reviewers dialog box displayed the changed file as \u0027b/gen.py as Not found\u0027, so there was no reviewers listed.",
      "revId": "ab5965c1d1faabee0d01472c7b4c6d2df418b0e6",
      "serverId": "c360c8e5-7aa8-3905-a7a0-810934766dac"
    }
  ]
}